---
title: "Data Cleaning"
author: "Bri Baker"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(janitor)
library(sf)
library(raster)
library(tmap)
library(stringr)

```

```{r}
flowering_times <- read_csv(here("data/RSV_Flora_2020.csv")) %>%
  clean_names() %>% 
  dplyr::select(taxon, collecting, common_name, lifeform:dec) %>% 
  mutate(collecting = case_when(collecting == "X" ~ "yes",
                                TRUE ~ "no"),
         family = str_to_title(family),
         lifeform = str_to_lower(lifeform)) %>% 
  pivot_longer(cols = jan:dec, 
               values_drop_na = TRUE,
               names_to = "month") %>%
  mutate(month = str_to_title(month)) %>% 
  filter(collecting == "yes") %>% 
  dplyr::select(taxon, common_name:month)


write_csv(flowering_times, here("data/flowering_times.csv"))


natives_vcla <- read_csv(here("data/vc_la_native_plants.csv")) %>%   clean_names() %>% 
  mutate(date = ymd(date)) %>% 
  write_csv(here("data/natives_vcla.csv"))


collection_locations <- read_csv(here("data/RSV_Collection Locations_2020_BB.csv"))
  
```
```{r}
protected_areas <- read_sf(here("data/Protected Areas.kml")) %>% 
  clean_names()

locations <- protected_areas %>% 
  dplyr::select(name) %>% 
  group_by(name) %>% 
  summarise()
  

#ggplot()+
  #geom_sf(data = collection_areas, aes(fill = name))


natives_location <- natives_vcla %>% 
  st_as_sf(coords = c("longitude","latitude")) %>% 
  st_set_crs(st_crs(protected_areas))

collection_areas <- locations %>% 
  filter(name %in% c("Arroyo Sequit",
                     "Cheeseboro/ Palo Comado Canyons",
                     "Circle X Ranch",
                     "Deer Creek",
                     "Diamond X Ranch",
                     "King Gillette Ranch",
                     "Paramount Ranch",
                     "Rancho Sierra Vista/Satwiwa",
                     "Rocky Oaks",
                     "Solstice Canyon",
                     "Upper Solstice Canyon",
                     "Yellowhill",
                     "Zuma/Trancas Canyons"
  ))# 

st_write(collection_areas, here("data","loc.gpkg"),format = "GPKG")


plot(natives_location)

plot(collection_areas)
```


```{r}
species_desired <- unique(flowering_times$taxon)

natives_samo <- st_filter(natives_location,
                          collection_areas, 
                          join = st_within) %>% 
  filter(taxon %in% species_desired) %>% 
  dplyr::select(id, taxon, date, geometry)

st_write(natives_samo, here("data/desired_natives_samo.gpkg"), format = "GPKG", append = FALSE)

plot(natives_samo)

```
```{r}
 flowering_now <- flowering_times %>% 
      filter(month %in% c("May", "Jun")) %>% 
      dplyr::select(taxon, month) %>% 
  mutate(id = as.numeric(factor(taxon)))%>%
  pivot_wider(id_cols = id,
              names_from = month,
              values_from = taxon) 
      


```

```{r}
loc_place <- col_loc %>% 
      filter(name == "Paramount Ranch")

loc_time <- flowering_times %>% 
      filter(month == "May")

loc_flowering <- samo_plants %>% 
  filter(taxon %in% loc_time$taxon) %>% 
  st_filter(loc_place, join = st_within)

plot(loc_flowering)   
  

    tm_shape(loc_flowering)+
      tm_dots(col = "taxon") 
```


